package libusblibrary;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ingroup desc<br>
 * A structure representing the superspeed endpoint companion<br>
 * descriptor. This descriptor is documented in section 9.6.7 of<br>
 * the USB 3.0 specification. All multiple-byte fields are represented in<br>
 * host-endian format.<br>
 * <i>native declaration : libusb.h:247</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("LibusbLibrary") 
public class libusb_ss_endpoint_companion_descriptor extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public byte bLength() {
		return this.io.getByteField(this, 0);
	}
	@Field(0) 
	public libusb_ss_endpoint_companion_descriptor bLength(byte bLength) {
		this.io.setByteField(this, 0, bLength);
		return this;
	}
	@Field(1) 
	public byte bDescriptorType() {
		return this.io.getByteField(this, 1);
	}
	@Field(1) 
	public libusb_ss_endpoint_companion_descriptor bDescriptorType(byte bDescriptorType) {
		this.io.setByteField(this, 1, bDescriptorType);
		return this;
	}
	@Field(2) 
	public byte bMaxBurst() {
		return this.io.getByteField(this, 2);
	}
	@Field(2) 
	public libusb_ss_endpoint_companion_descriptor bMaxBurst(byte bMaxBurst) {
		this.io.setByteField(this, 2, bMaxBurst);
		return this;
	}
	@Field(3) 
	public byte bmAttributes() {
		return this.io.getByteField(this, 3);
	}
	@Field(3) 
	public libusb_ss_endpoint_companion_descriptor bmAttributes(byte bmAttributes) {
		this.io.setByteField(this, 3, bmAttributes);
		return this;
	}
	@Field(4) 
	public short wBytesPerInterval() {
		return this.io.getShortField(this, 4);
	}
	@Field(4) 
	public libusb_ss_endpoint_companion_descriptor wBytesPerInterval(short wBytesPerInterval) {
		this.io.setShortField(this, 4, wBytesPerInterval);
		return this;
	}
	public libusb_ss_endpoint_companion_descriptor() {
		super();
	}
	public libusb_ss_endpoint_companion_descriptor(Pointer pointer) {
		super(pointer);
	}
}
