package libusblibrary;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
import org.bridj.ann.Union;
/**
 * <i>native declaration : libusb.h:1189</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Union 
@Library("LibusbLibrary") 
public class libusb_cpu_to_le16__tmp_union extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : uint8_t[2] */
	@Array({2}) 
	@Field(0) 
	public Pointer<Byte > b8() {
		return this.io.getPointerField(this, 0);
	}
	@Field(1) 
	public short b16() {
		return this.io.getShortField(this, 1);
	}
	@Field(1) 
	public libusb_cpu_to_le16__tmp_union b16(short b16) {
		this.io.setShortField(this, 1, b16);
		return this;
	}
	public libusb_cpu_to_le16__tmp_union() {
		super();
	}
	public libusb_cpu_to_le16__tmp_union(Pointer pointer) {
		super(pointer);
	}
}
