__LINE__=__LINE__
__FILE__=__FILE__
__COUNTER__=__COUNTER__
__cplusplus=__cplusplus => 1
__LITTLE_ENDIAN__=__LITTLE_ENDIAN__ => 1
G_BYTE_ORDER=G_BYTE_ORDER => 1234
NDEBUG=NDEBUG => 1
__STDC__=__STDC__ => 1
HAVE_PROTOTYPES=HAVE_PROTOTYPES => 1
STDC_HEADERS=STDC_HEADERS => 1
_CHAR_UNSIGNED=_CHAR_UNSIGNED => 1
WIN32_LEAN_AND_MEAN=WIN32_LEAN_AND_MEAN => 1
_WCHAR_T_DEFINED=_WCHAR_T_DEFINED => 1
_NATIVE_WCHAR_T_DEFINED=_NATIVE_WCHAR_T_DEFINED => 1
_MSC_VER=_MSC_VER => 1100
WINAPI=WINAPI => __stdcall
TARGET_CPU_X86=TARGET_CPU_X86 => 1
__i386__=__i386__ => 1
M_I86=M_I86 => 1
_M_I86=_M_I86 => 1
_WIN32=_WIN32 => 1
__attribute__=__attribute__(x)
LIBUSB_H=LIBUSB_H
_SSIZE_T_DEFINED=_SSIZE_T_DEFINED
LIBUSB_DEPRECATED_FOR=LIBUSB_DEPRECATED_FOR(f)
LIBUSB_CALL=LIBUSB_CALL => WINAPI
LIBUSB_API_VERSION=LIBUSB_API_VERSION => 0x01000103
LIBUSBX_API_VERSION=LIBUSBX_API_VERSION => LIBUSB_API_VERSION
libusb_le16_to_cpu=libusb_le16_to_cpu => libusb_cpu_to_le16
LIBUSB_DT_DEVICE_SIZE=LIBUSB_DT_DEVICE_SIZE => 18
LIBUSB_DT_CONFIG_SIZE=LIBUSB_DT_CONFIG_SIZE => 9
LIBUSB_DT_INTERFACE_SIZE=LIBUSB_DT_INTERFACE_SIZE => 9
LIBUSB_DT_ENDPOINT_SIZE=LIBUSB_DT_ENDPOINT_SIZE => 7
LIBUSB_DT_ENDPOINT_AUDIO_SIZE=LIBUSB_DT_ENDPOINT_AUDIO_SIZE => 9
LIBUSB_DT_HUB_NONVAR_SIZE=LIBUSB_DT_HUB_NONVAR_SIZE => 7
LIBUSB_DT_SS_ENDPOINT_COMPANION_SIZE=LIBUSB_DT_SS_ENDPOINT_COMPANION_SIZE => 6
LIBUSB_DT_BOS_SIZE=LIBUSB_DT_BOS_SIZE => 5
LIBUSB_DT_DEVICE_CAPABILITY_SIZE=LIBUSB_DT_DEVICE_CAPABILITY_SIZE => 3
LIBUSB_BT_USB_2_0_EXTENSION_SIZE=LIBUSB_BT_USB_2_0_EXTENSION_SIZE => 7
LIBUSB_BT_SS_USB_DEVICE_CAPABILITY_SIZE=LIBUSB_BT_SS_USB_DEVICE_CAPABILITY_SIZE => 10
LIBUSB_BT_CONTAINER_ID_SIZE=LIBUSB_BT_CONTAINER_ID_SIZE => 20
LIBUSB_DT_BOS_MAX_SIZE=LIBUSB_DT_BOS_MAX_SIZE => ((LIBUSB_DT_BOS_SIZE) + (LIBUSB_BT_USB_2_0_EXTENSION_SIZE) + (LIBUSB_BT_SS_USB_DEVICE_CAPABILITY_SIZE) + (LIBUSB_BT_CONTAINER_ID_SIZE))
LIBUSB_ENDPOINT_ADDRESS_MASK=LIBUSB_ENDPOINT_ADDRESS_MASK => 0x0f
LIBUSB_ENDPOINT_DIR_MASK=LIBUSB_ENDPOINT_DIR_MASK => 0x80
LIBUSB_TRANSFER_TYPE_MASK=LIBUSB_TRANSFER_TYPE_MASK => 0x03
LIBUSB_ISO_SYNC_TYPE_MASK=LIBUSB_ISO_SYNC_TYPE_MASK => 0x0C
LIBUSB_ISO_USAGE_TYPE_MASK=LIBUSB_ISO_USAGE_TYPE_MASK => 0x30
LIBUSB_CONTROL_SETUP_SIZE=LIBUSB_CONTROL_SETUP_SIZE => (sizeof(struct libusb_control_setup))
LIBUSB_ERROR_COUNT=LIBUSB_ERROR_COUNT => 14
LIBUSB_HOTPLUG_MATCH_ANY=LIBUSB_HOTPLUG_MATCH_ANY => -1
