package eduonix.nativeapp.libusb;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ingroup desc
<br>
 * A structure representing the standard USB device descriptor. This
<br>
 * descriptor is documented in section 9.6.1 of the USB 3.0 specification.
<br>
 * All multiple-byte fields are represented in host-endian format.<br>
 * <i>native declaration : libusb.h:168</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("C:\\Users\\ubu\\eduonixnativeapps\\genwrap\\libusb")
public class libusb_device_descriptor extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public byte bLength() {
		return this.io.getByteField(this, 0);
	}
	@Field(0) 
	public libusb_device_descriptor bLength(byte bLength) {
		this.io.setByteField(this, 0, bLength);
		return this;
	}
	@Field(1) 
	public byte bDescriptorType() {
		return this.io.getByteField(this, 1);
	}
	@Field(1) 
	public libusb_device_descriptor bDescriptorType(byte bDescriptorType) {
		this.io.setByteField(this, 1, bDescriptorType);
		return this;
	}
	@Field(2) 
	public short bcdUSB() {
		return this.io.getShortField(this, 2);
	}
	@Field(2) 
	public libusb_device_descriptor bcdUSB(short bcdUSB) {
		this.io.setShortField(this, 2, bcdUSB);
		return this;
	}
	@Field(3) 
	public byte bDeviceClass() {
		return this.io.getByteField(this, 3);
	}
	@Field(3) 
	public libusb_device_descriptor bDeviceClass(byte bDeviceClass) {
		this.io.setByteField(this, 3, bDeviceClass);
		return this;
	}
	@Field(4) 
	public byte bDeviceSubClass() {
		return this.io.getByteField(this, 4);
	}
	@Field(4) 
	public libusb_device_descriptor bDeviceSubClass(byte bDeviceSubClass) {
		this.io.setByteField(this, 4, bDeviceSubClass);
		return this;
	}
	@Field(5) 
	public byte bDeviceProtocol() {
		return this.io.getByteField(this, 5);
	}
	@Field(5) 
	public libusb_device_descriptor bDeviceProtocol(byte bDeviceProtocol) {
		this.io.setByteField(this, 5, bDeviceProtocol);
		return this;
	}
	@Field(6) 
	public byte bMaxPacketSize0() {
		return this.io.getByteField(this, 6);
	}
	@Field(6) 
	public libusb_device_descriptor bMaxPacketSize0(byte bMaxPacketSize0) {
		this.io.setByteField(this, 6, bMaxPacketSize0);
		return this;
	}
	@Field(7) 
	public short idVendor() {
		return this.io.getShortField(this, 7);
	}
	@Field(7) 
	public libusb_device_descriptor idVendor(short idVendor) {
		this.io.setShortField(this, 7, idVendor);
		return this;
	}
	@Field(8) 
	public short idProduct() {
		return this.io.getShortField(this, 8);
	}
	@Field(8) 
	public libusb_device_descriptor idProduct(short idProduct) {
		this.io.setShortField(this, 8, idProduct);
		return this;
	}
	@Field(9) 
	public short bcdDevice() {
		return this.io.getShortField(this, 9);
	}
	@Field(9) 
	public libusb_device_descriptor bcdDevice(short bcdDevice) {
		this.io.setShortField(this, 9, bcdDevice);
		return this;
	}
	@Field(10) 
	public byte iManufacturer() {
		return this.io.getByteField(this, 10);
	}
	@Field(10) 
	public libusb_device_descriptor iManufacturer(byte iManufacturer) {
		this.io.setByteField(this, 10, iManufacturer);
		return this;
	}
	@Field(11) 
	public byte iProduct() {
		return this.io.getByteField(this, 11);
	}
	@Field(11) 
	public libusb_device_descriptor iProduct(byte iProduct) {
		this.io.setByteField(this, 11, iProduct);
		return this;
	}
	@Field(12) 
	public byte iSerialNumber() {
		return this.io.getByteField(this, 12);
	}
	@Field(12) 
	public libusb_device_descriptor iSerialNumber(byte iSerialNumber) {
		this.io.setByteField(this, 12, iSerialNumber);
		return this;
	}
	@Field(13) 
	public byte bNumConfigurations() {
		return this.io.getByteField(this, 13);
	}
	@Field(13) 
	public libusb_device_descriptor bNumConfigurations(byte bNumConfigurations) {
		this.io.setByteField(this, 13, bNumConfigurations);
		return this;
	}
	public libusb_device_descriptor() {
		super();
	}
	public libusb_device_descriptor(Pointer pointer) {
		super(pointer);
	}
}
