package eduonix.nativeapp.libusb;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ingroup desc
<br>
 * A structure representing the Binary Device Object Store (BOS) descriptor.
<br>
 * This descriptor is documented in section 9.6.2 of the USB 3.0 specification.
<br>
 * All multiple-byte fields are represented in host-endian format.<br>
 * <i>native declaration : libusb.h:272</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("C:\\Users\\ubu\\eduonixnativeapps\\genwrap\\libusb")
public class libusb_bos_descriptor extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public byte bLength() {
		return this.io.getByteField(this, 0);
	}
	@Field(0) 
	public libusb_bos_descriptor bLength(byte bLength) {
		this.io.setByteField(this, 0, bLength);
		return this;
	}
	@Field(1) 
	public byte bDescriptorType() {
		return this.io.getByteField(this, 1);
	}
	@Field(1) 
	public libusb_bos_descriptor bDescriptorType(byte bDescriptorType) {
		this.io.setByteField(this, 1, bDescriptorType);
		return this;
	}
	@Field(2) 
	public short wTotalLength() {
		return this.io.getShortField(this, 2);
	}
	@Field(2) 
	public libusb_bos_descriptor wTotalLength(short wTotalLength) {
		this.io.setShortField(this, 2, wTotalLength);
		return this;
	}
	@Field(3) 
	public byte bNumDeviceCaps() {
		return this.io.getByteField(this, 3);
	}
	@Field(3) 
	public libusb_bos_descriptor bNumDeviceCaps(byte bNumDeviceCaps) {
		this.io.setByteField(this, 3, bNumDeviceCaps);
		return this;
	}
	/** C type : libusb_bos_dev_capability_descriptor*[0] */
	@Array({0}) 
	@Field(4) 
	public Pointer<Pointer<libusb_bos_dev_capability_descriptor > > dev_capability() {
		return this.io.getPointerField(this, 4);
	}
	public libusb_bos_descriptor() {
		super();
	}
	public libusb_bos_descriptor(Pointer pointer) {
		super(pointer);
	}
}
