package eduonix.nativeapp.libusb;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ingroup lib
<br>
 * Structure providing the version of the libusb runtime<br>
 * <i>native declaration : libusb.h:341</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("C:\\Users\\ubu\\eduonixnativeapps\\genwrap\\libusb")
public class libusb_version extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public short major() {
		return this.io.getShortField(this, 0);
	}
	@Field(0) 
	public libusb_version major(short major) {
		this.io.setShortField(this, 0, major);
		return this;
	}
	@Field(1) 
	public short minor() {
		return this.io.getShortField(this, 1);
	}
	@Field(1) 
	public libusb_version minor(short minor) {
		this.io.setShortField(this, 1, minor);
		return this;
	}
	@Field(2) 
	public short micro() {
		return this.io.getShortField(this, 2);
	}
	@Field(2) 
	public libusb_version micro(short micro) {
		this.io.setShortField(this, 2, micro);
		return this;
	}
	@Field(3) 
	public short nano() {
		return this.io.getShortField(this, 3);
	}
	@Field(3) 
	public libusb_version nano(short nano) {
		this.io.setShortField(this, 3, nano);
		return this;
	}
	/** C type : const char* */
	@Field(4) 
	public Pointer<Byte > rc() {
		return this.io.getPointerField(this, 4);
	}
	/** C type : const char* */
	@Field(4) 
	public libusb_version rc(Pointer<Byte > rc) {
		this.io.setPointerField(this, 4, rc);
		return this;
	}
	/** C type : const char* */
	@Field(5) 
	public Pointer<Byte > describe() {
		return this.io.getPointerField(this, 5);
	}
	/** C type : const char* */
	@Field(5) 
	public libusb_version describe(Pointer<Byte > describe) {
		this.io.setPointerField(this, 5, describe);
		return this;
	}
	public libusb_version() {
		super();
	}
	public libusb_version(Pointer pointer) {
		super(pointer);
	}
}
