package libusb;
import libusb.LibusbLibrary.libusb_device_handle;
import libusb.LibusbLibrary.libusb_transfer_cb_fn;
import libusb.LibusbLibrary.libusb_transfer_status;
import org.bridj.BridJ;
import org.bridj.IntValuedEnum;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Array;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ingroup asyncio<br>
 * The generic USB transfer structure. The user populates this structure and<br>
 * then submits it in order to request a transfer. After the transfer has<br>
 * completed, the library populates the transfer with the results and passes<br>
 * it back to the user.<br>
 * <i>native declaration : libusb.h:531</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("libusb") 
public class libusb_transfer extends StructObject {
	static {
		BridJ.register();
	}
	/** C type : libusb_device_handle* */
	@Field(0) 
	public Pointer<libusb_device_handle > dev_handle() {
		return this.io.getPointerField(this, 0);
	}
	/** C type : libusb_device_handle* */
	@Field(0) 
	public libusb_transfer dev_handle(Pointer<libusb_device_handle > dev_handle) {
		this.io.setPointerField(this, 0, dev_handle);
		return this;
	}
	@Field(1) 
	public byte flags() {
		return this.io.getByteField(this, 1);
	}
	@Field(1) 
	public libusb_transfer flags(byte flags) {
		this.io.setByteField(this, 1, flags);
		return this;
	}
	@Field(2) 
	public byte endpoint() {
		return this.io.getByteField(this, 2);
	}
	@Field(2) 
	public libusb_transfer endpoint(byte endpoint) {
		this.io.setByteField(this, 2, endpoint);
		return this;
	}
	@Field(3) 
	public byte type() {
		return this.io.getByteField(this, 3);
	}
	@Field(3) 
	public libusb_transfer type(byte type) {
		this.io.setByteField(this, 3, type);
		return this;
	}
	@Field(4) 
	public int timeout() {
		return this.io.getIntField(this, 4);
	}
	@Field(4) 
	public libusb_transfer timeout(int timeout) {
		this.io.setIntField(this, 4, timeout);
		return this;
	}
	/** C type : libusb_transfer_status */
	@Field(5) 
	public IntValuedEnum<libusb_transfer_status > status() {
		return this.io.getEnumField(this, 5);
	}
	/** C type : libusb_transfer_status */
	@Field(5) 
	public libusb_transfer status(IntValuedEnum<libusb_transfer_status > status) {
		this.io.setEnumField(this, 5, status);
		return this;
	}
	@Field(6) 
	public int length() {
		return this.io.getIntField(this, 6);
	}
	@Field(6) 
	public libusb_transfer length(int length) {
		this.io.setIntField(this, 6, length);
		return this;
	}
	@Field(7) 
	public int actual_length() {
		return this.io.getIntField(this, 7);
	}
	@Field(7) 
	public libusb_transfer actual_length(int actual_length) {
		this.io.setIntField(this, 7, actual_length);
		return this;
	}
	/** C type : libusb_transfer_cb_fn */
	@Field(8) 
	public Pointer<libusb_transfer_cb_fn > callback() {
		return this.io.getPointerField(this, 8);
	}
	/** C type : libusb_transfer_cb_fn */
	@Field(8) 
	public libusb_transfer callback(Pointer<libusb_transfer_cb_fn > callback) {
		this.io.setPointerField(this, 8, callback);
		return this;
	}
	/** C type : void* */
	@Field(9) 
	public Pointer<? > user_data() {
		return this.io.getPointerField(this, 9);
	}
	/** C type : void* */
	@Field(9) 
	public libusb_transfer user_data(Pointer<? > user_data) {
		this.io.setPointerField(this, 9, user_data);
		return this;
	}
	/** C type : unsigned char* */
	@Field(10) 
	public Pointer<Byte > buffer() {
		return this.io.getPointerField(this, 10);
	}
	/** C type : unsigned char* */
	@Field(10) 
	public libusb_transfer buffer(Pointer<Byte > buffer) {
		this.io.setPointerField(this, 10, buffer);
		return this;
	}
	@Field(11) 
	public int num_iso_packets() {
		return this.io.getIntField(this, 11);
	}
	@Field(11) 
	public libusb_transfer num_iso_packets(int num_iso_packets) {
		this.io.setIntField(this, 11, num_iso_packets);
		return this;
	}
	/** C type : libusb_iso_packet_descriptor[0] */
	@Array({0}) 
	@Field(12) 
	public Pointer<libusb_iso_packet_descriptor > iso_packet_desc() {
		return this.io.getPointerField(this, 12);
	}
	public libusb_transfer() {
		super();
	}
	public libusb_transfer(Pointer pointer) {
		super(pointer);
	}
}
