package libusb;
import org.bridj.BridJ;
import org.bridj.Pointer;
import org.bridj.StructObject;
import org.bridj.ann.Field;
import org.bridj.ann.Library;
/**
 * \ingroup desc<br>
 * A structure representing the USB 2.0 Extension descriptor<br>
 * This descriptor is documented in section 9.6.2.1 of the USB 3.0 specification.<br>
 * All multiple-byte fields are represented in host-endian format.<br>
 * <i>native declaration : libusb.h:284</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> or <a href="http://bridj.googlecode.com/">BridJ</a> .
 */
@Library("libusb") 
public class libusb_usb_2_0_extension_descriptor extends StructObject {
	static {
		BridJ.register();
	}
	@Field(0) 
	public byte bLength() {
		return this.io.getByteField(this, 0);
	}
	@Field(0) 
	public libusb_usb_2_0_extension_descriptor bLength(byte bLength) {
		this.io.setByteField(this, 0, bLength);
		return this;
	}
	@Field(1) 
	public byte bDescriptorType() {
		return this.io.getByteField(this, 1);
	}
	@Field(1) 
	public libusb_usb_2_0_extension_descriptor bDescriptorType(byte bDescriptorType) {
		this.io.setByteField(this, 1, bDescriptorType);
		return this;
	}
	@Field(2) 
	public byte bDevCapabilityType() {
		return this.io.getByteField(this, 2);
	}
	@Field(2) 
	public libusb_usb_2_0_extension_descriptor bDevCapabilityType(byte bDevCapabilityType) {
		this.io.setByteField(this, 2, bDevCapabilityType);
		return this;
	}
	@Field(3) 
	public int bmAttributes() {
		return this.io.getIntField(this, 3);
	}
	@Field(3) 
	public libusb_usb_2_0_extension_descriptor bmAttributes(int bmAttributes) {
		this.io.setIntField(this, 3, bmAttributes);
		return this;
	}
	public libusb_usb_2_0_extension_descriptor() {
		super();
	}
	public libusb_usb_2_0_extension_descriptor(Pointer pointer) {
		super(pointer);
	}
}
